//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisionTrainer.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ApplicationResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("VisionTrainer.Resources.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NavigationTestTitle {
            get {
                return ResourceManager.GetString("NavigationTestTitle", resourceCulture);
            }
        }
        
        internal static string NavigationTrainTitle {
            get {
                return ResourceManager.GetString("NavigationTrainTitle", resourceCulture);
            }
        }
        
        internal static string NavigationSettingsTitle {
            get {
                return ResourceManager.GetString("NavigationSettingsTitle", resourceCulture);
            }
        }
        
        internal static string PageCaptureTitle {
            get {
                return ResourceManager.GetString("PageCaptureTitle", resourceCulture);
            }
        }
        
        internal static string PagePredictionInputTitle {
            get {
                return ResourceManager.GetString("PagePredictionInputTitle", resourceCulture);
            }
        }
        
        internal static string PagePredictionInputUploading {
            get {
                return ResourceManager.GetString("PagePredictionInputUploading", resourceCulture);
            }
        }
        
        internal static string PageCaptureToolbarBrowsePhotos {
            get {
                return ResourceManager.GetString("PageCaptureToolbarBrowsePhotos", resourceCulture);
            }
        }
        
        internal static string PageCaptureToolbarToggleCamera {
            get {
                return ResourceManager.GetString("PageCaptureToolbarToggleCamera", resourceCulture);
            }
        }
        
        internal static string PageCaptureImageUploading {
            get {
                return ResourceManager.GetString("PageCaptureImageUploading", resourceCulture);
            }
        }
        
        internal static string PagePermissionsTitle {
            get {
                return ResourceManager.GetString("PagePermissionsTitle", resourceCulture);
            }
        }
        
        internal static string PagePermissionsMessage {
            get {
                return ResourceManager.GetString("PagePermissionsMessage", resourceCulture);
            }
        }
        
        internal static string PagePermissionsCameraButton {
            get {
                return ResourceManager.GetString("PagePermissionsCameraButton", resourceCulture);
            }
        }
        
        internal static string PagePermissionsPhotosButton {
            get {
                return ResourceManager.GetString("PagePermissionsPhotosButton", resourceCulture);
            }
        }
        
        internal static string PageTrainTitle {
            get {
                return ResourceManager.GetString("PageTrainTitle", resourceCulture);
            }
        }
        
        internal static string PageMediaDetailTitle {
            get {
                return ResourceManager.GetString("PageMediaDetailTitle", resourceCulture);
            }
        }
        
        internal static string PageBrowseMediaTitle {
            get {
                return ResourceManager.GetString("PageBrowseMediaTitle", resourceCulture);
            }
        }
        
        internal static string PageBrowseMediaTagPrompt {
            get {
                return ResourceManager.GetString("PageBrowseMediaTagPrompt", resourceCulture);
            }
        }
        
        internal static string PageBrowseMediaRemovePhotoPrompt {
            get {
                return ResourceManager.GetString("PageBrowseMediaRemovePhotoPrompt", resourceCulture);
            }
        }
        
        internal static string PageBrowseMediaRemoveConfirm {
            get {
                return ResourceManager.GetString("PageBrowseMediaRemoveConfirm", resourceCulture);
            }
        }
        
        internal static string PagePredictionResultsTitle {
            get {
                return ResourceManager.GetString("PagePredictionResultsTitle", resourceCulture);
            }
        }
        
        internal static string CameraNotSupported {
            get {
                return ResourceManager.GetString("CameraNotSupported", resourceCulture);
            }
        }
        
        internal static string CameraPermissionMissing {
            get {
                return ResourceManager.GetString("CameraPermissionMissing", resourceCulture);
            }
        }
        
        internal static string CameraPermissionGranted {
            get {
                return ResourceManager.GetString("CameraPermissionGranted", resourceCulture);
            }
        }
        
        internal static string CameraPermissionDeniedTitle {
            get {
                return ResourceManager.GetString("CameraPermissionDeniedTitle", resourceCulture);
            }
        }
        
        internal static string CameraPermissionDeniedMessage {
            get {
                return ResourceManager.GetString("CameraPermissionDeniedMessage", resourceCulture);
            }
        }
        
        internal static string CameraPermissionPromptTitle {
            get {
                return ResourceManager.GetString("CameraPermissionPromptTitle", resourceCulture);
            }
        }
        
        internal static string CameraPermissionPromptMessage {
            get {
                return ResourceManager.GetString("CameraPermissionPromptMessage", resourceCulture);
            }
        }
        
        internal static string PhotosNotSupported {
            get {
                return ResourceManager.GetString("PhotosNotSupported", resourceCulture);
            }
        }
        
        internal static string PhotosPermissionMissing {
            get {
                return ResourceManager.GetString("PhotosPermissionMissing", resourceCulture);
            }
        }
        
        internal static string PhotosPermissionGranted {
            get {
                return ResourceManager.GetString("PhotosPermissionGranted", resourceCulture);
            }
        }
        
        internal static string PhotosPermissionDeniedTitle {
            get {
                return ResourceManager.GetString("PhotosPermissionDeniedTitle", resourceCulture);
            }
        }
        
        internal static string PhotosPermissionDeniedMessage {
            get {
                return ResourceManager.GetString("PhotosPermissionDeniedMessage", resourceCulture);
            }
        }
        
        internal static string PhotosPermissionPromptTitle {
            get {
                return ResourceManager.GetString("PhotosPermissionPromptTitle", resourceCulture);
            }
        }
        
        internal static string PhotosPermissionPromptMessage {
            get {
                return ResourceManager.GetString("PhotosPermissionPromptMessage", resourceCulture);
            }
        }
        
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string GeneralErrorTitle {
            get {
                return ResourceManager.GetString("GeneralErrorTitle", resourceCulture);
            }
        }
        
        internal static string GeneralErrorSummary {
            get {
                return ResourceManager.GetString("GeneralErrorSummary", resourceCulture);
            }
        }
    }
}
